# Generated by Django 5.0.4 on 2026-03-02 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setores', '0002_setor_responsavel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('lido', models.BooleanField(default=False)),
                ('curtidas', models.PositiveIntegerField(default=0)),
                ('categoria', models.CharField(choices=[('SUGE', 'Sugestão'), ('ELOG', 'Elogio'), ('RECL', 'Reclamação'), ('ENPS', 'eNPS')], default='SUGE', max_length=4)),
                ('nota_enps', models.PositiveIntegerField(blank=True, null=True)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='setores.setor')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_resposta', models.TextField()),
                ('data_resposta', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resposta', to='feedbacks.feedback')),
            ],
        ),
    ]
