# Generated by Django 5.2.5 on 2026-03-02 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='sentimento',
            field=models.CharField(blank=True, choices=[('Positivo', 'Positivo'), ('Negativo', 'Negativo'), ('Neutro', 'Neutro')], default='Neutro', max_length=20, null=True),
        ),
    ]
