# Generated by Django 5.0.4 on 2026-03-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_feedback_sentimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_sensivel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='protocolo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='categoria',
            field=models.CharField(choices=[('SUGE', 'Sugestão'), ('ELOG', 'Elogio'), ('RECL', 'Reclamação'), ('ENPS', 'eNPS'), ('DENU', 'Denúncia')], default='SUGE', max_length=4),
        ),
    ]
