# Generated by Django 5.0.4 on 2026-03-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0003_feedback_is_sensivel_feedback_protocolo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('AVIS', 'Aviso'), ('IMPO', 'Importante'), ('DEST', 'Destaque')], default='AVIS', max_length=4)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
