# Generated by Django 5.0.4 on 2026-03-03 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setores', '0002_setor_responsavel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesquisaClima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='clima.pesquisaclima')),
            ],
        ),
        migrations.CreateModel(
            name='RespostaClima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_satisfacao', models.PositiveIntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('sentimento', models.CharField(choices=[('Positivo', 'Positivo'), ('Negativo', 'Negativo'), ('Neutro', 'Neutro')], default='Neutro', max_length=20)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='clima.pesquisaclima')),
                ('setor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='setores.setor')),
            ],
        ),
    ]
