# Generated by Django 5.0.4 on 2026-03-03 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0001_initial'),
        ('setores', '0002_setor_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='obrigatoria',
            field=models.BooleanField(default=True, verbose_name='É obrigatória?'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='tipo',
            field=models.CharField(choices=[('NOTA', 'Escala de Emoji (1-5)'), ('TEXTO', 'Resposta Discursiva (Texto)')], default='NOTA', max_length=10, verbose_name='Tipo de Resposta'),
        ),
        migrations.AddField(
            model_name='pesquisaclima',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='texto',
            field=models.CharField(max_length=255, verbose_name='Pergunta'),
        ),
        migrations.AlterField(
            model_name='pesquisaclima',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='respostaclima',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setores.setor'),
        ),
    ]
