# Generated by Django 5.0.4 on 2026-03-04 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0002_pergunta_obrigatoria_pergunta_tipo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pesquisaclima',
            options={'verbose_name': 'Pesquisa de Clima', 'verbose_name_plural': 'Pesquisas de Clima'},
        ),
        migrations.RemoveField(
            model_name='respostaclima',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='respostaclima',
            name='nota_satisfacao',
        ),
        migrations.AddField(
            model_name='respostaclima',
            name='comentario_ia',
            field=models.TextField(blank=True, null=True, verbose_name='Comentário para IA'),
        ),
        migrations.AddField(
            model_name='respostaclima',
            name='nota_enps',
            field=models.PositiveIntegerField(default=0, verbose_name='Nota eNPS (0-10)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pesquisaclima',
            name='ativa',
            field=models.BooleanField(default=True, verbose_name='Pesquisa Ativa?'),
        ),
        migrations.AlterField(
            model_name='pesquisaclima',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição/Objetivo'),
        ),
        migrations.AlterField(
            model_name='pesquisaclima',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título da Pesquisa'),
        ),
        migrations.CreateModel(
            name='RespostaPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_texto', models.TextField(blank=True, null=True)),
                ('resposta_nota', models.PositiveIntegerField(blank=True, null=True)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clima.pergunta')),
                ('resposta_clima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='clima.respostaclima')),
            ],
        ),
    ]
